### PR TITLE
Enable specifying user-defined object metadata

### PR DESCRIPTION
**Pull request by AndreasDahl**
See https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata

### CODE REVIEW

**Comment by AndreasDahl** [comment]
@andersfugmann I would like to support adding [User-defined object metadata](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata). Please let me know if you prefer another way of doing this.

**Review by andersfugmann — CHANGES_REQUESTED** [review]
LGTM, but how would a user of the API get hold of the metadata? Would it make sense to extend  `head` to also return metadata headers (extending the `content` record)? 

Also there is no documentation on the extra optional argument. I know the documentation is slightly sparse currently, but we should at least document addition of new parameters.

**Comment by AndreasDahl** [comment]
I added documentation for the new parameter and started looking into supporting the User-defined metadata for the `head` call, but i am running into a crash when trying to do even a basic `head` call (without any changes). The stack trace looks like this:
```
(monitor.ml.Error (Failure "[line 1, col 1] unexpected end of input")
 ("Raised at Ezxmlm.from_input in file \"lib/ezxmlm.ml\", line 28, characters 4-72"
  "Called from Ezxmlm.from_string in file \"lib/ezxmlm.ml\", line 37, characters 18-30"
  "Called from Aws_s3__S3.xmlm_of_string in file \"aws-s3/s3.ml\", line 22, characters 22-47"
  "Called from Aws_s3__S3.Make.do_command.(fun) in file \"aws-s3/s3.ml\", line 254, characters 18-37"
  "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69"
  "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 167, characters 6-47"))
```
I'm not sure if i am doing something wrong or if perhaps amazon changed something over the years. What about we leave that feature (user-defined metadata headers for the `head` call) for a future PR?

**Comment by andersfugmann** [comment]
Thats odd. 
I don't have access to an aws s3 account, so I cannot verify breakage, but the `head` command works against a `minio` server, and the [aws documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html) states that
> The current version of the Amazon S3 API is 2006-03-01
So I would be quite surprised if the api has changed. 

How did you test the `head` command? There is a command line client (`aws_cli_async` / ` aws_cli_lwt`), which installs with the package (or found under `_build/default/aws-s3-async/bin/aws_cli_async.exe`). Is works almost interchangeably with the `aws s3` command.

Anyways, I'm working on updating the code to latest versions, and will create a new version "soon-ish". Seems the package is broken for newer versions of `cmdliner` and `core`, which I would like to fix before releasing a new version.

**Comment by andersfugmann** [comment]
Release 4.6.0 is available though opam, which includes this PR. I did manage to extend the logic for HEAD to return user supplied headers.

**Pull request merged**
